version: '3'
services:
  mongodb:
    ports:
      - "27017:27017"
    image: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - my-mongo-db:/data/db
  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
volumes:
  my-mongo-db: 
    driver: local
