# Stage 1: Build Stage
FROM node:20-alpine AS build

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN yarn

# Copy all application files
COPY . .

# Generate Prisma client
RUN npx prisma generate

RUN yarn build

# Start the application in production mode
FROM node:20-alpine AS production

WORKDIR /

COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/yarn.lock ./
COPY --from=build /app/.env ./
COPY --from=build /app/prisma ./prisma

# RUN npx prisma generate

EXPOSE 4000

CMD ["node", "dist/src/main"]
