export enum CodeFlowType {
  FORMDS = "FORMDS",
  INDEED = "INDEED",
  LINKEDIN_JOB_POST = "LINKEDIN_JOB_POST",
  BUSINESS_NEWS = "BUSINESS_NEWS",
  PR_NEWS = "PR_NEWS",
  NEW_HIRES = "NEW_HIRES",
  GOOGLE_FUNDING = "GOOGLE_FUNDING"
}
