// Don't try to modify this code manually 
// This code generated by console from webapp
// You can copy and paste from dev build 

export const routes = {
  home: {
    match: '/',
    label: 'home',
    name: 'HOME',
  },
  twoStepAuth: {
    match: '/settings/preferences/two-step-auth',
    label: 'two-step-auth',
    name: 'TWO_STEP_AUTH',
  },
  login: {
    match: '/login',
    label: 'login',
    name: 'LOGIN',
  },
  unauthorized: {
    match: '/unauthorized',
    label: 'unauthorized',
    name: 'UNAUTHORIZED',
  },
  oktaLogin: {
    match: '/okta',
    label: 'okta',
    name: 'OKTA',
  },
  oktaCallBack: {
    match: '/okta/callback',
    label: 'callback',
    name: 'OKTA_CALLBACK',
  },
  logout: {
    match: '/logout',
    label: 'logout',
    name: 'LOGOUT',
  },
  forgetPassword: {
    match: '/forgot_password',
    label: 'forgot_password',
    name: 'ForgotPassword',
  },
  passwordReset: {
    match: '/forgot_password/:token',
    label: ':token',
    name: 'ResetPassword',
  },
  setPassword: {
    match: '/welcome/:welcomeToken',
    label: ':welcomeToken',
    name: 'SetAccountPassword',
  },
  companies: {
    match: '/companies/list',
    label: 'Companies',
    name: 'CompanyList',
  },
  companyDetail: {
    match: '/companies/:id',
    label: 'company detail',
    name: 'CompanyDetails',
  },
  companyTickets: {
    match: '/companies/:id/tickets',
    label: 'tickets',
    name: 'CompanyTicketList',
  },
  companyContacts: {
    name: 'ContactList',
    match: '/companies/:id/contacts',
    label: 'Contact',
  },
  companyEventDetail: {
    name: 'EventDetails',
    label: 'Details',
    match: '/companies/event/:companyId/:id',
  },
  companyRatings: {
    name: 'RATINGS',
    match: '/ratings',
    label: 'Rating',
  },
  companyRating: {
    name: 'RATING',
    match: '/rating',
    label: 'Add Rating',
  },
  companyDetailRating: {
    name: 'RatingDetails',
    match: '/ratingdetails',
    label: 'Rating Details',
  },
  companyContact: {
    name: 'ContactList',
    match: '/companies/contact/:id',
    label: 'contact detail',
  },
  companyDataSource: {
    match: '/companies/:id/data-source',
    label: 'data-source',
    name: 'COMPANY_DATA_SOURCE',
  },
  companyFeedback: {
    match: '/companies/:id/feedback',
    label: 'feedback',
    name: 'COMPANY_FEEDBACK',
  },
  competitors: {
    name: 'CompetitorsList',
    match: '/companies/:id/competitors',
    label: 'competitors',
  },
  companyTimeline: {
    name: 'CompanyTimeline',
    match: '/companies/timeline',
    label: 'Companies Timeline',
  },
  products: {
    name: 'ProductList',
    match: '/companies/:id/products',
    label: 'product list',
  },
  productDetail: {
    name: 'ProductDetails',
    label: 'Product detail',
    match: '/products/:id',
  },
  companyProductDetail: {
    name: 'ProductDetails',
    label: 'Product detail',
    match: '/companies/products/:id',
  },
  events: {
    name: 'EventList',
    match: '/events',
    label: 'Events',
  },
  eventDetail: {
    name: 'EventDetails',
    label: 'detail',
    match: '/events/:id',
  },
  notes: {
    name: 'NotesScreen',
    match: '/settings/preferences/notes',
    label: 'Notes',
  },
  eventNotes: {
    name: 'NotesScreen',
    match: '/events/:id/notes',
    label: 'Notes',
  },
  companyNotes: {
    name: 'CompanyNoteList',
    match: '/companies/:id/notes',
    label: 'Notes',
  },
  notesCreate: {
    name: 'NOTE_CREATE',
    match: '/settings/preferences/notes/create',
    label: 'Note Create',
  },
  noteDetail: {
    name: 'NoteDetailsScreen',
    match: '/settings/preferences/notes/:id',
    label: 'Note Details',
  },
  editNote: {
    match: '/settings/preferences/notes/edit/:id',
    label: 'Note Edit',
    name: 'EDIT_NOTE',
  },
  message: {
    name: 'Notes',
    match: '/message',
    label: 'Messages',
  },
  messageCreate: {
    name: 'CreateNote',
    match: '/message-create',
    label: 'Messages Create',
  },
  editMessage: {
    match: '/message/edit/:id',
    label: 'message edit',
    name: 'EditNote',
  },
  messageDetail: {
    match: '/message/:id',
    label: 'message detail',
    name: 'NoteDetailsScreen',
  },
  messageThread: {
    name: 'NoteDetailsScreen',
    match: '/message-thread/:id',
    label: 'Messages Thread',
  },
  dataObjectCreate: {
    name: 'DataObjectCreate',
    match: '/settings/admin/data-objects/create',
    label: 'Object Create',
  },
  dataObjects: {
    name: 'DataObjects',
    label: 'Data Object',
    match: '/settings/admin/data-objects',
  },
  dataObjectsDetails: {
    name: 'DataObjectDetails',
    match: '/settings/admin/data-objects/details',
    label: 'Data Object',
  },
  thresholdScreen: {
    match: '/settings/admin/threshold',
    label: 'threshold',
    name: 'THRESHOLD',
  },
  companyReferences: {
    name: 'ReferencesList',
    label: "Company's References",
    match: '/companies/:id/references',
  },
  addCustomerReference: {
    match: '/companies/:id/reference/add',
    label: 'add reference',
    name: 'CustomerReference',
  },
  addOpportunityReference: {
    match: '/customer/:id/reference/add',
    label: 'add customer reference',
    name: 'OpportunityReference',
  },
  launchedList: {
    name: 'LaunchList',
    match: '/events/launched-list',
    label: 'Launched List',
  },
  launchedCompanyList: {
    name: 'LaunchList',
    match: '/companies/launched-list',
    label: 'Launched List',
  },
  launchedDetail: {
    match: '/companies/launch/:launchId',
    label: 'detail',
    name: 'LaunchDetails',
  },
  companyOpportunities: {
    name: 'OpportunityList',
    label: "Company's Opportunity",
    match: '/companies/:companyId/opportunities',
  },
  companyOpportunityDetail: {
    name: 'OpportunityDetails',
    match: '/companies/:companyId/opportunities/:opportunityId',
    label: 'Opportunities',
  },
  launchedEventDetail: {
    match: '/events/launch/:launchId',
    label: 'detail',
    name: 'LaunchDetails',
  },
  selectTemplate: {
    match: '/companies/launch/select-template',
    name: 'SelectTemplate',
    label: 'Select Template',
  },
  selectEventTemplate: {
    name: 'SelectEventTemplate',
    match: '/events/launch/select-template',
    label: 'Select Template',
  },
  launchEmail: {
    name: 'LaunchCreate',
    match: '/events/launch/create',
    label: 'Launch template',
  },
  admin: {
    name: 'Admin',
    match: '/settings/admin',
    label: 'Admin',
  },
  userListGrid: {
    name: 'UserListAdmin',
    match: '/settings/admin/user-list',
    label: 'User List',
  },
  selectedUserListGrid: {
    name: 'SelectedUserList',
    match: '/settings/admin/selected-user-list',
    label: 'Selected User List',
  },
  userListGridForGroup: {
    name: 'UpdateGroup',
    match: '/settings/admin/user-list-for-group',
    label: 'Update Group',
  },
  updateUser: {
    name: 'UpdateUser',
    match: '/settings/admin/user/update-user/:id',
    label: 'update user',
  },
  UserDetailScreen: {
    name: 'UpdateUserDetails',
    match: '/settings/admin/user-list/details/:id',
    label: 'User Details',
  },
  UserDetails: {
    name: 'UpdateUserDetails',
    match: '/settings/admin/user-list/details/:id/details',
    label: 'User Details',
  },
  UserDetailsUpdate: {
    name: 'UpdateUserDetails',
    match: '/settings/admin/user/details/:id/update',
    label: 'User Details',
  },
  userCompanyAccess: {
    name: 'UserCompanyAccess',
    match: '/settings/admin/user-list/details/:id/company-access',
    label: 'User company access',
  },
  userInheritedPermission: {
    name: 'UserPermission',
    label: 'User Details',
    match: '/settings/admin/user/permission',
  },
  settingsUserUploadCSVFile: {
    match: '/settings/admin/user-list/upload-csv-file',
    label: 'upload-csv-file',
    name: 'UploadCsv',
  },
  createUserGroup: {
    match: '/settings/admin/user-groups/create',
    label: 'New user group',
    name: 'CreateUserGroup',
  },
  editUserGroup: {
    name: 'EditUserGroup',
    label: 'Edit User Group',
    match: '/settings/admin/user-groups/create',
  },
  userGroupAction: {
    name: 'UserGroupAction',
    label: 'Create User Action',
    match: '/settings/admin/user-group-action',
  },
  settingsGroups: {
    match: '/settings/admin/groups',
    label: 'groups',
    name: 'USER_GROUPS_LIST',
  },
  groupDetails: {
    name: 'UserGroupDetails',
    label: 'group details',
    match: '/settings/admin/user-groups/details/:id',
  },
  groupList: {
    name: 'UserGroupList',
    label: 'Group List',
    match: '/settings/admin/user-groups',
  },
  templateList: {
    name: 'TemplateList',
    match: '/settings/templates/list',
    label: 'Template List',
  },
  templateAdd: {
    match: '/settings/templates/add',
    label: 'add',
    name: 'TemplateAdd',
  },
  templateEdit: {
    match: '/settings/templates/list/edit/:id',
    label: 'Email template',
    name: 'TemplateEdit',
  },
  templateDetails: {
    match: '/settings/templates/list/detail/:id',
    label: 'Email template',
    name: 'TemplateDetails',
  },
  roleList: {
    match: '/settings/admin/roles',
    label: 'roles',
    name: 'RoleList',
  },
  roleDetails: {
    match: '/settings/admin/roles/details',
    label: 'details',
    name: 'RoleDetails',
  },
  roleCreate: {
    match: '/settings/admin/roles/create',
    label: 'create',
    name: 'RoleCreate',
  },
  roleEdit: {
    match: '/settings/admin/roles/details/:id',
    label: 'Role Management',
    name: 'RoleEdit',
  },
  useCaseList: {
    name: 'UseCases',
    label: 'Use Cases',
    match: '/settings/admin/use-cases',
  },
  useCaseDetails: {
    name: 'UseCasesDetails',
    match: '/settings/admin/use-cases/detail',
    label: 'Use Case Management',
  },
  useCaseCreate: {
    match: '/settings/admin/use-cases/create',
    label: 'Create Use Case',
    name: 'UseCaseCreate',
  },
  integrationLists: {
    match: '/settings/admin/integrations',
    label: 'integrations',
    name: 'integrationList',
  },
  integrationDetails: {
    match: '/settings/admin/integrations/:id',
    label: 'Integrations',
    name: 'IntegrationDetails',
  },
  integrationOkta: {
    name: 'IntegrationOkta',
    match: '/settings/admin/integrations/okta',
    label: 'Okta Settings',
  },
  companyGroupCreate: {
    name: 'CompanyGroupCrate',
    label: 'Company Group Create',
    match: '/settings/admin/company-management-list/create',
  },
  companyGroupEdit: {
    match: '/settings/admin/company-management-list/edit/:id',
    label: 'Company Group edit',
    name: 'CompanyGroupEdit',
  },
  companyMgmtDetail: {
    name: 'CompanyGroupDetail',
    match: '/settings/admin/company-management-list/:id',
    label: 'Company Detail',
  },
  companyGroupList: {
    name: 'CompanyGroupList',
    label: 'Company Group List',
    match: '/settings/admin/company-management-list/group',
  },
  companyList: {
    name: 'CompanyListAdmin',
    match: '/settings/admin/company-management-list',
    label: 'Company List',
  },
  selectedCompanyList: {
    name: 'SelectedCompanyListAdmin',
    match: '/settings/admin/company-management-list/selected',
    label: 'Selected Company List',
  },
  settingsEmail: {
    match: '/settings/messages/email',
    label: 'email',
    name: 'CompanyListAdmin',
  },
  sourceSystem: {
    match: '/admin/source-system',
    label: 'source-system',
    name: 'SourceSystem',
  },
  dashboardPipelineScreen: {
    match: '/dashboard/pipeline',
    label: 'pipeline',
    name: 'Pipeline',
  },
  dashboardPipelineDetailScreen: {
    match: '/dashboard/pipeline/:id',
    label: 'Pipeline Detail',
    name: 'PipelineDetails',
  },
  dashboardTeamScreen: {
    match: '/dashboard/team',
    label: 'team',
    name: 'DashboardTeamScreen',
  },
  dashboardTeamDetailScreen: {
    name: 'DashboardTeamDetails',
    match: '/dashboard/team/:id',
    label: 'Team Detail',
  },
  dashboardEvent: {
    match: '/dashboard/company',
    label: 'company',
    name: 'DashboardEvent',
  },
  dashboardMe: {
    match: '/dashboard/me',
    label: 'me',
    name: 'DashboardMe',
  },
  settings: {
    match: '/settings',
    label: 'settings',
    name: 'Settings',
  },
  settingsAdmin: {
    match: '/settings/admin/main',
    label: 'main',
    name: 'AdminMain',
  },
  settingsNotifications: {
    match: '/settings/preferences/notifications',
    label: 'notifications',
    name: 'Notifications',
  },
  settingsProfile: {
    match: '/settings/preferences/profile',
    label: 'profile',
    name: 'Profile',
  },
  settingsResetPassword: {
    match: '/settings/preferences/reset-password',
    label: 'reset-password',
    name: 'ResetPassword',
  },
  feedback: {
    match: '/feedback',
    label: 'feedback',
    name: 'Feedback',
  },
  superUserLogin: {
    match: '/super-admin/login',
    label: 'login',
    name: 'SuperAdminLogin',
  },
  superUserForgetPassword: {
    match: '/super-admin/forgot_password',
    label: 'forgot_password',
    name: 'super_admin_forget_password_step_1',
  },
  superUserPasswordReset: {
    match: '/super-admin/forgot_password/:token',
    label: ':token',
    name: 'super_admin_forget_password_step_2',
  },
  superUserChangePassword: {
    match: '/super-admin/settings/reset-password',
    label: 'reset-password',
    name: 'super_admin_change_password',
  },
  controlPanelScreen: {
    match: '/super-admin/settings/control-panel',
    label: 'control-panel',
    name: 'super_admin_control_panel',
  },
  reportScreen: {
    name: 'super_admin_report',
    match: '/super-admin/report/:id',
    label: 'Report',
  },
};
